// <auto-generated />
namespace TravelExpress5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class firstMigration4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstMigration4));
        
        string IMigrationMetadata.Id
        {
            get { return "201906121917225_firstMigration4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
